name: Build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, windows-latest, windows-2019, macos-latest, macos-14,	macos-13, ubuntu-24.04-arm, ubuntu-22.04-arm]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        cpp_compiler: [g++, clang++, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-2019
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-22.04
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-22.04
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-20.04
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-20.04
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-24.04-arm
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-24.04-arm
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-22.04-arm
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-22.04-arm
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-14
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-13
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
            c_compiler: clang
            cpp_compiler: g++
          - os: windows-2019
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-2019
            cpp_compiler: g++
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-24.04
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-22.04
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-20.04
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-22.04-arm
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-24.04-arm
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-14
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-14
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-13
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-13
            c_compiler: cl
            cpp_compiler: cl

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build C++ Runtime
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j4

      - name: Prepare C++ Test Data
        run: cp -r ${{ github.workspace }}/test_data ${{ steps.strings.outputs.build-output-dir }}/test/unit/test_data

      - name: Run C++ Runtime Tests
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }} --verbose

      - name: Setup Python Virtual Environment
        if: runner.os != 'windows'
        shell: bash
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip

      - name: Build Python wheel
        if: runner.os != 'windows'
        shell: bash
        run: |
          . .venv/bin/activate
          cd ${{ github.workspace }}/python/magnetron_framework
          pip wheel --verbose -w dist .

      - name: Install Python wheel
        if: runner.os != 'windows'
        shell: bash
        run: |
          . .venv/bin/activate
          pip install ${{ github.workspace }}/python/magnetron_framework/dist/*.whl

      - name: Install Pytest
        if: runner.os != 'windows'
        shell: bash
        run: |
          . .venv/bin/activate
          pip install pytest

      - name: Run Python Tests
        if: runner.os != 'windows'
        shell: bash
        run: |
          . .venv/bin/activate
          python -m pytest ${{ github.workspace }}/python/tests/*